/*
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.knetikcloud.api;

import com.knetikcloud.client.ApiException;
import com.knetikcloud.model.PageResourceUserSidResource;
import com.knetikcloud.model.Result;
import com.knetikcloud.model.UserSidResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthUsersApi
 */
@Ignore
public class AuthUsersApiTest {

    private final AuthUsersApi api = new AuthUsersApi();

    
    /**
     * Add a sid to a user
     *
     * No error returned if the user already has the sid. &lt;b&gt;Resources Needed:&lt;/b&gt; ROLE_SUPER_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addSidTest() throws ApiException {
        Integer userId = null;
        UserSidResource sid = null;
        UserSidResource response = api.addSid(userId, sid);

        // TODO: test validations
    }
    
    /**
     * Get a user sid
     *
     * Http error 404 means the user does not have the sid&lt;b&gt;Resources Needed:&lt;/b&gt; VIEW_ACCESS
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSidTest() throws ApiException {
        Integer userId = null;
        String sid = null;
        UserSidResource response = api.getSid(userId, sid);

        // TODO: test validations
    }
    
    /**
     * List and search user sids
     *
     * &lt;b&gt;Resources Needed:&lt;/b&gt; VIEW_ACCESS
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSidsTest() throws ApiException {
        Integer userId = null;
        Integer size = null;
        Integer page = null;
        String order = null;
        PageResourceUserSidResource response = api.getSids(userId, size, page, order);

        // TODO: test validations
    }
    
    /**
     * Remove a sid from a user
     *
     * No error returned if the suer does not have the sid. &lt;b&gt;Resources Needed:&lt;/b&gt; ROLE_SUPER_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeSidTest() throws ApiException {
        Integer userId = null;
        String sid = null;
        api.removeSid(userId, sid);

        // TODO: test validations
    }
    
}
