/*
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.knetikcloud.api;

import com.knetikcloud.client.ApiException;
import com.knetikcloud.model.PageResourceTemplateResource;
import com.knetikcloud.model.PatchResource;
import com.knetikcloud.model.Result;
import com.knetikcloud.model.TemplateResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LevelingApi
 */
@Ignore
public class LevelingApiTest {

    private final LevelingApi api = new LevelingApi();

    
    /**
     * Create a leveling template
     *
     * Leveling Templates define a type of level schema and the properties they have.&lt;br /&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; POST
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createLevelingTemplateTest() throws ApiException {
        TemplateResource levelingTemplateResource = null;
        TemplateResource response = api.createLevelingTemplate(levelingTemplateResource);

        // TODO: test validations
    }
    
    /**
     * Delete a leveling template
     *
     * If cascade &#x3D; &#39;detach&#39;, it will force delete the template even if it&#39;s attached to other objects.&lt;br /&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; DELETE
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteLevelingTemplateTest() throws ApiException {
        String id = null;
        String cascade = null;
        api.deleteLevelingTemplate(id, cascade);

        // TODO: test validations
    }
    
    /**
     * Get a single leveling template
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; GET
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLevelingTemplateTest() throws ApiException {
        String id = null;
        TemplateResource response = api.getLevelingTemplate(id);

        // TODO: test validations
    }
    
    /**
     * List and search leveling templates
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; LIST
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLevelingTemplatesTest() throws ApiException {
        Integer size = null;
        Integer page = null;
        String order = null;
        PageResourceTemplateResource response = api.getLevelingTemplates(size, page, order);

        // TODO: test validations
    }
    
    /**
     * Update a leveling template
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; PUT
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateLevelingTemplateTest() throws ApiException {
        String id = null;
        PatchResource templatePatchResource = null;
        Boolean testValidation = null;
        TemplateResource response = api.updateLevelingTemplate(id, templatePatchResource, testValidation);

        // TODO: test validations
    }
    
}
