/*
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.knetikcloud.api;

import com.knetikcloud.client.ApiException;
import com.knetikcloud.model.DocumentRemoveRequest;
import com.knetikcloud.model.ReindexRequest;
import com.knetikcloud.model.Result;
import com.knetikcloud.model.SearchDocument;
import com.knetikcloud.model.SearchQuery;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SearchApi
 */
@Ignore
public class SearchApiTest {

    private final SearchApi api = new SearchApi();

    
    /**
     * Adds a document to be indexed. For system use only.
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH_MANAGEMENT
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void indexDocumentTest() throws ApiException {
        SearchDocument document = null;
        api.indexDocument(document);

        // TODO: test validations
    }
    
    /**
     * Triggers a full re-indexing of all documents of the specified type. For system use only.
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH_MANAGEMENT
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void reindexAllTest() throws ApiException {
        ReindexRequest request = null;
        api.reindexAll(request);

        // TODO: test validations
    }
    
    /**
     * Remove a document from the index. For system use only.
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH_MANAGEMENT
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeDocumentTest() throws ApiException {
        DocumentRemoveRequest request = null;
        api.removeDocument(request);

        // TODO: test validations
    }
    
    /**
     * Count matches with no template
     *
     * This is a 1 to 1 mapping of a ElasticSearch call to _count.  Further information can be found at their &lt;a href&#x3D;&#39;https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html&#39;&gt;API guide&lt;/a&gt;. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchCountGETTest() throws ApiException {
        String type = null;
        Object response = api.searchCountGET(type);

        // TODO: test validations
    }
    
    /**
     * Count matches with no template
     *
     * This is a 1 to 1 mapping of a ElasticSearch call to _count.  Further information can be found at their &lt;a href&#x3D;&#39;https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html&#39;&gt;API guide&lt;/a&gt;. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchCountPOSTTest() throws ApiException {
        String type = null;
        Object query = null;
        Object response = api.searchCountPOST(type, query);

        // TODO: test validations
    }
    
    /**
     * Get document with no template
     *
     * This is a 1 to 1 mapping of a ElasticSearch call.  Further information can be found at their &lt;a href&#x3D;&#39;https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html&#39;&gt;API guide&lt;/a&gt;. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchDocumentGETTest() throws ApiException {
        String type = null;
        String id = null;
        Object response = api.searchDocumentGET(type, id);

        // TODO: test validations
    }
    
    /**
     * Explain matches with no template
     *
     * This is a 1 to 1 mapping of a ElasticSearch call to _explain.  Further information can be found at their &lt;a href&#x3D;&#39;https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html&#39;&gt;API guide&lt;/a&gt;. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchExplainGETTest() throws ApiException {
        String type = null;
        String id = null;
        Object response = api.searchExplainGET(type, id);

        // TODO: test validations
    }
    
    /**
     * Explain matches with no template
     *
     * This is a 1 to 1 mapping of a ElasticSearch call to _explain.  Further information can be found at their &lt;a href&#x3D;&#39;https://www.elastic.co/guide/en/elasticsearch/reference/current/search-count.html&#39;&gt;API guide&lt;/a&gt;. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchExplainPOSTTest() throws ApiException {
        String type = null;
        String id = null;
        Object query = null;
        Object response = api.searchExplainPOST(type, id, query);

        // TODO: test validations
    }
    
    /**
     * Search an index with no template
     *
     * This is a 1 to 1 mapping of a ElasticSearch call to _search.  Further information can be found at their &lt;a href&#x3D;&#39;https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html&#39;&gt;API guide&lt;/a&gt;. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchIndexTest() throws ApiException {
        String type = null;
        Object query = null;
        Object response = api.searchIndex(type, query);

        // TODO: test validations
    }
    
    /**
     * Search an index with no template
     *
     * This is a 1 to 1 mapping of a ElasticSearch call to _search.  Further information can be found at their &lt;a href&#x3D;&#39;https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html&#39;&gt;API guide&lt;/a&gt;. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchIndexGETTest() throws ApiException {
        String type = null;
        Object response = api.searchIndexGET(type);

        // TODO: test validations
    }
    
    /**
     * Get indices
     *
     * This is a 1 to 1 mapping of a ElasticSearch call to _cat/indices for indices.  Further information can be found at their &lt;a href&#x3D;&#39;https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html&#39;&gt;API guide&lt;/a&gt;. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchIndicesGETTest() throws ApiException {
        Object response = api.searchIndicesGET();

        // TODO: test validations
    }
    
    /**
     * Get mapping with no template
     *
     * This is a 1 to 1 mapping of a ElasticSearch call to _mapping.  Further information can be found at their &lt;a href&#x3D;&#39;https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-mapping.html&#39;&gt;API guide&lt;/a&gt;. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchMappingsGETTest() throws ApiException {
        String type = null;
        Object response = api.searchMappingsGET(type);

        // TODO: test validations
    }
    
    /**
     * Search public index with no template
     *
     * Make an ElasticSearch query against a public index. Results filtered for records the caller has GET permission on. Further information on query format can be found at their &lt;a href&#x3D;&#39;https://www.elastic.co/guide/en/elasticsearch/reference/current/search.html&#39;&gt;API guide&lt;/a&gt;. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH_ADMIN
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchPublicIndexTest() throws ApiException {
        String type = null;
        Integer user = null;
        SearchQuery query = null;
        Object response = api.searchPublicIndex(type, user, query);

        // TODO: test validations
    }
    
    /**
     * Validate matches with no template
     *
     * This is a 1 to 1 mapping of a ElasticSearch call to _validate/query.  Further information can be found at their &lt;a href&#x3D;&#39;https://www.elastic.co/guide/en/elasticsearch/reference/current/search-validate.html&#39;&gt;API guide&lt;/a&gt;. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchValidateGETTest() throws ApiException {
        String type = null;
        Object response = api.searchValidateGET(type);

        // TODO: test validations
    }
    
    /**
     * Validate matches with no template
     *
     * This is a 1 to 1 mapping of a ElasticSearch call to _validate/query.  Further information can be found at their &lt;a href&#x3D;&#39;https://www.elastic.co/guide/en/elasticsearch/reference/current/search-validate.html&#39;&gt;API guide&lt;/a&gt;. &lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; SEARCH
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchValidatePOSTTest() throws ApiException {
        String type = null;
        Object query = null;
        Object response = api.searchValidatePOST(type, query);

        // TODO: test validations
    }
    
}
