/*
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.knetikcloud.api;

import com.knetikcloud.client.ApiException;
import com.knetikcloud.model.BasicTemplatedResource;
import com.knetikcloud.model.PageResourceTemplateResource;
import com.knetikcloud.model.PatchResource;
import com.knetikcloud.model.Result;
import com.knetikcloud.model.TemplateResource;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TemplatesApi
 */
@Ignore
public class TemplatesApiTest {

    private final TemplatesApi api = new TemplatesApi();

    
    /**
     * Create a template
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; TEMPLATES_ADMIN&lt;br /&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; POST
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTemplateTest() throws ApiException {
        String typeHint = null;
        TemplateResource template = null;
        TemplateResource response = api.createTemplate(typeHint, template);

        // TODO: test validations
    }
    
    /**
     * Delete a template
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; TEMPLATES_ADMIN&lt;br /&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; DELETE
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTemplateTest() throws ApiException {
        String typeHint = null;
        String id = null;
        String cascade = null;
        api.deleteTemplate(typeHint, id, cascade);

        // TODO: test validations
    }
    
    /**
     * Get a template
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; TEMPLATES_ADMIN&lt;br /&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; GET
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTemplateTest() throws ApiException {
        String typeHint = null;
        String id = null;
        TemplateResource response = api.getTemplate(typeHint, id);

        // TODO: test validations
    }
    
    /**
     * List and search templates
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; TEMPLATES_ADMIN&lt;br /&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; LIST
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTemplatesTest() throws ApiException {
        String typeHint = null;
        Integer size = null;
        Integer page = null;
        String order = null;
        PageResourceTemplateResource response = api.getTemplates(typeHint, size, page, order);

        // TODO: test validations
    }
    
    /**
     * Patch a template
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; TEMPLATES_ADMIN&lt;br /&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; PUT
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchTemplateTest() throws ApiException {
        String typeHint = null;
        String id = null;
        PatchResource templatePatchResource = null;
        Boolean testValidation = null;
        api.patchTemplate(typeHint, id, templatePatchResource, testValidation);

        // TODO: test validations
    }
    
    /**
     * Validate a templated resource
     *
     * Error code thrown if invalid.&lt;br&gt;&lt;br&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; TEMPLATES_ADMIN&lt;br /&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; GET
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void validateTest() throws ApiException {
        String typeHint = null;
        BasicTemplatedResource resource = null;
        api.validate(typeHint, resource);

        // TODO: test validations
    }
    
}
