/*
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.knetikcloud.api;

import com.knetikcloud.client.ApiException;
import com.knetikcloud.model.PageResourceTemplateResource;
import com.knetikcloud.model.PageResourceVerificationRequest;
import com.knetikcloud.model.PatchResource;
import com.knetikcloud.model.Result;
import com.knetikcloud.model.TemplateResource;
import com.knetikcloud.model.VerificationRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VerificationApi
 */
@Ignore
public class VerificationApiTest {

    private final VerificationApi api = new VerificationApi();

    
    /**
     * Create a request template
     *
     * Request Templates define a type of request and the properties they have.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createRequestTemplateTest() throws ApiException {
        TemplateResource requestTemplateResource = null;
        TemplateResource response = api.createRequestTemplate(requestTemplateResource);

        // TODO: test validations
    }
    
    /**
     * Create a new request
     *
     * Verification requests ask for a user to respond and confirm something, like their email address of an invitation to join a group.&lt;br /&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; POST
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createVerificationRequestTest() throws ApiException {
        VerificationRequest verificationRequest = null;
        VerificationRequest response = api.createVerificationRequest(verificationRequest);

        // TODO: test validations
    }
    
    /**
     * Delete a request template
     *
     * If cascade &#x3D; &#39;detach&#39;, it will force delete the template even if it&#39;s attached to other objects.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteRequestTemplateTest() throws ApiException {
        String id = null;
        String cascade = null;
        api.deleteRequestTemplate(id, cascade);

        // TODO: test validations
    }
    
    /**
     * Delete an existing request
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; DELETE
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteVerificationRequestTest() throws ApiException {
        String code = null;
        api.deleteVerificationRequest(code);

        // TODO: test validations
    }
    
    /**
     * Get a single request template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRequestTemplateTest() throws ApiException {
        String id = null;
        TemplateResource response = api.getRequestTemplate(id);

        // TODO: test validations
    }
    
    /**
     * List and search request templates
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRequestTemplatesTest() throws ApiException {
        Integer size = null;
        Integer page = null;
        String order = null;
        PageResourceTemplateResource response = api.getRequestTemplates(size, page, order);

        // TODO: test validations
    }
    
    /**
     * Get a single verification request
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; GET
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVerificationRequestTest() throws ApiException {
        String code = null;
        VerificationRequest response = api.getVerificationRequest(code);

        // TODO: test validations
    }
    
    /**
     * List requests
     *
     * Get a list of verification requests.&lt;br /&gt;&lt;b&gt;Permissions Needed:&lt;/b&gt; LIST
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVerificationRequestsTest() throws ApiException {
        Integer size = null;
        Integer page = null;
        String order = null;
        PageResourceVerificationRequest response = api.getVerificationRequests(size, page, order);

        // TODO: test validations
    }
    
    /**
     * Update a request template
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateRequestTemplateTest() throws ApiException {
        String id = null;
        PatchResource templatePatchResource = null;
        Boolean testValidation = null;
        TemplateResource response = api.updateRequestTemplate(id, templatePatchResource, testValidation);

        // TODO: test validations
    }
    
    /**
     * Update an existing request
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; PUT
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateVerificationRequestTest() throws ApiException {
        String code = null;
        VerificationRequest verificationRequest = null;
        VerificationRequest response = api.updateVerificationRequest(code, verificationRequest);

        // TODO: test validations
    }
    
    /**
     * Verify a request
     *
     * &lt;b&gt;Permissions Needed:&lt;/b&gt; VERIFY
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verifyRequestTest() throws ApiException {
        String code = null;
        VerificationRequest response = api.verifyRequest(code);

        // TODO: test validations
    }
    
}
