/*
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.knetikcloud.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * InnerQuery
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-22T09:26:09.103-05:00")
public class InnerQuery {
  @JsonProperty("bool")
  private Object bool = null;

  public InnerQuery bool(Object bool) {
    this.bool = bool;
    return this;
  }

   /**
   * The &#39;bool&#39; body of an elastic search query. Will be augmented to enforce security.
   * @return bool
  **/
  @ApiModelProperty(required = true, value = "The 'bool' body of an elastic search query. Will be augmented to enforce security.")
  public Object getBool() {
    return bool;
  }

  public void setBool(Object bool) {
    this.bool = bool;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InnerQuery innerQuery = (InnerQuery) o;
    return Objects.equals(this.bool, innerQuery.bool);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bool);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InnerQuery {\n");
    
    sb.append("    bool: ").append(toIndentedString(bool)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

