/*
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.knetikcloud.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * QuickBuyRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-05T11:01:12.134-05:00")
public class QuickBuyRequest {
  @JsonProperty("address1")
  private String address1 = null;

  @JsonProperty("address2")
  private String address2 = null;

  @JsonProperty("billing_address1")
  private String billingAddress1 = null;

  @JsonProperty("billing_address2")
  private String billingAddress2 = null;

  @JsonProperty("billing_city_name")
  private String billingCityName = null;

  @JsonProperty("billing_country_name")
  private String billingCountryName = null;

  @JsonProperty("billing_full_name")
  private String billingFullName = null;

  @JsonProperty("billing_postal_code")
  private String billingPostalCode = null;

  @JsonProperty("billing_state_name")
  private String billingStateName = null;

  @JsonProperty("city_name")
  private String cityName = null;

  @JsonProperty("country_name")
  private String countryName = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("name_prefix")
  private String namePrefix = null;

  @JsonProperty("postal_code")
  private String postalCode = null;

  @JsonProperty("sku")
  private String sku = null;

  @JsonProperty("state_name")
  private String stateName = null;

  @JsonProperty("user_id")
  private Integer userId = null;

  public QuickBuyRequest address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * Line one of the customer&#39;s shipping address
   * @return address1
  **/
  @ApiModelProperty(value = "Line one of the customer's shipping address")
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public QuickBuyRequest address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * Line two of the customer&#39;s shipping address
   * @return address2
  **/
  @ApiModelProperty(value = "Line two of the customer's shipping address")
  public String getAddress2() {
    return address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public QuickBuyRequest billingAddress1(String billingAddress1) {
    this.billingAddress1 = billingAddress1;
    return this;
  }

   /**
   * Line one of the customer&#39;s billing address
   * @return billingAddress1
  **/
  @ApiModelProperty(value = "Line one of the customer's billing address")
  public String getBillingAddress1() {
    return billingAddress1;
  }

  public void setBillingAddress1(String billingAddress1) {
    this.billingAddress1 = billingAddress1;
  }

  public QuickBuyRequest billingAddress2(String billingAddress2) {
    this.billingAddress2 = billingAddress2;
    return this;
  }

   /**
   * Line two of the customer&#39;s billing address
   * @return billingAddress2
  **/
  @ApiModelProperty(value = "Line two of the customer's billing address")
  public String getBillingAddress2() {
    return billingAddress2;
  }

  public void setBillingAddress2(String billingAddress2) {
    this.billingAddress2 = billingAddress2;
  }

  public QuickBuyRequest billingCityName(String billingCityName) {
    this.billingCityName = billingCityName;
    return this;
  }

   /**
   * The city for the customer&#39;s billing address
   * @return billingCityName
  **/
  @ApiModelProperty(value = "The city for the customer's billing address")
  public String getBillingCityName() {
    return billingCityName;
  }

  public void setBillingCityName(String billingCityName) {
    this.billingCityName = billingCityName;
  }

  public QuickBuyRequest billingCountryName(String billingCountryName) {
    this.billingCountryName = billingCountryName;
    return this;
  }

   /**
   * The country for the customer&#39;s billing address
   * @return billingCountryName
  **/
  @ApiModelProperty(value = "The country for the customer's billing address")
  public String getBillingCountryName() {
    return billingCountryName;
  }

  public void setBillingCountryName(String billingCountryName) {
    this.billingCountryName = billingCountryName;
  }

  public QuickBuyRequest billingFullName(String billingFullName) {
    this.billingFullName = billingFullName;
    return this;
  }

   /**
   * The customer&#39;s name for the billing address
   * @return billingFullName
  **/
  @ApiModelProperty(value = "The customer's name for the billing address")
  public String getBillingFullName() {
    return billingFullName;
  }

  public void setBillingFullName(String billingFullName) {
    this.billingFullName = billingFullName;
  }

  public QuickBuyRequest billingPostalCode(String billingPostalCode) {
    this.billingPostalCode = billingPostalCode;
    return this;
  }

   /**
   * The postal code for the customer&#39;s billing address
   * @return billingPostalCode
  **/
  @ApiModelProperty(value = "The postal code for the customer's billing address")
  public String getBillingPostalCode() {
    return billingPostalCode;
  }

  public void setBillingPostalCode(String billingPostalCode) {
    this.billingPostalCode = billingPostalCode;
  }

  public QuickBuyRequest billingStateName(String billingStateName) {
    this.billingStateName = billingStateName;
    return this;
  }

   /**
   * The state for the customer&#39;s billing address
   * @return billingStateName
  **/
  @ApiModelProperty(value = "The state for the customer's billing address")
  public String getBillingStateName() {
    return billingStateName;
  }

  public void setBillingStateName(String billingStateName) {
    this.billingStateName = billingStateName;
  }

  public QuickBuyRequest cityName(String cityName) {
    this.cityName = cityName;
    return this;
  }

   /**
   * The city for the customer&#39;s shipping address
   * @return cityName
  **/
  @ApiModelProperty(value = "The city for the customer's shipping address")
  public String getCityName() {
    return cityName;
  }

  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  public QuickBuyRequest countryName(String countryName) {
    this.countryName = countryName;
    return this;
  }

   /**
   * The country for the customer&#39;s shipping address
   * @return countryName
  **/
  @ApiModelProperty(value = "The country for the customer's shipping address")
  public String getCountryName() {
    return countryName;
  }

  public void setCountryName(String countryName) {
    this.countryName = countryName;
  }

  public QuickBuyRequest email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The customer&#39;s email address
   * @return email
  **/
  @ApiModelProperty(value = "The customer's email address")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public QuickBuyRequest namePrefix(String namePrefix) {
    this.namePrefix = namePrefix;
    return this;
  }

   /**
   * The customer&#39;s name prefix
   * @return namePrefix
  **/
  @ApiModelProperty(value = "The customer's name prefix")
  public String getNamePrefix() {
    return namePrefix;
  }

  public void setNamePrefix(String namePrefix) {
    this.namePrefix = namePrefix;
  }

  public QuickBuyRequest postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * The postal code for the customer&#39;s shipping address
   * @return postalCode
  **/
  @ApiModelProperty(value = "The postal code for the customer's shipping address")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public QuickBuyRequest sku(String sku) {
    this.sku = sku;
    return this;
  }

   /**
   * SKU of item being purchased
   * @return sku
  **/
  @ApiModelProperty(required = true, value = "SKU of item being purchased")
  public String getSku() {
    return sku;
  }

  public void setSku(String sku) {
    this.sku = sku;
  }

  public QuickBuyRequest stateName(String stateName) {
    this.stateName = stateName;
    return this;
  }

   /**
   * The state for the customer&#39;s shipping address
   * @return stateName
  **/
  @ApiModelProperty(value = "The state for the customer's shipping address")
  public String getStateName() {
    return stateName;
  }

  public void setStateName(String stateName) {
    this.stateName = stateName;
  }

  public QuickBuyRequest userId(Integer userId) {
    this.userId = userId;
    return this;
  }

   /**
   * ID of the user making the purchase. If null, currently logged in user will be used.
   * @return userId
  **/
  @ApiModelProperty(value = "ID of the user making the purchase. If null, currently logged in user will be used.")
  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuickBuyRequest quickBuyRequest = (QuickBuyRequest) o;
    return Objects.equals(this.address1, quickBuyRequest.address1) &&
        Objects.equals(this.address2, quickBuyRequest.address2) &&
        Objects.equals(this.billingAddress1, quickBuyRequest.billingAddress1) &&
        Objects.equals(this.billingAddress2, quickBuyRequest.billingAddress2) &&
        Objects.equals(this.billingCityName, quickBuyRequest.billingCityName) &&
        Objects.equals(this.billingCountryName, quickBuyRequest.billingCountryName) &&
        Objects.equals(this.billingFullName, quickBuyRequest.billingFullName) &&
        Objects.equals(this.billingPostalCode, quickBuyRequest.billingPostalCode) &&
        Objects.equals(this.billingStateName, quickBuyRequest.billingStateName) &&
        Objects.equals(this.cityName, quickBuyRequest.cityName) &&
        Objects.equals(this.countryName, quickBuyRequest.countryName) &&
        Objects.equals(this.email, quickBuyRequest.email) &&
        Objects.equals(this.namePrefix, quickBuyRequest.namePrefix) &&
        Objects.equals(this.postalCode, quickBuyRequest.postalCode) &&
        Objects.equals(this.sku, quickBuyRequest.sku) &&
        Objects.equals(this.stateName, quickBuyRequest.stateName) &&
        Objects.equals(this.userId, quickBuyRequest.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address1, address2, billingAddress1, billingAddress2, billingCityName, billingCountryName, billingFullName, billingPostalCode, billingStateName, cityName, countryName, email, namePrefix, postalCode, sku, stateName, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuickBuyRequest {\n");
    
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    billingAddress1: ").append(toIndentedString(billingAddress1)).append("\n");
    sb.append("    billingAddress2: ").append(toIndentedString(billingAddress2)).append("\n");
    sb.append("    billingCityName: ").append(toIndentedString(billingCityName)).append("\n");
    sb.append("    billingCountryName: ").append(toIndentedString(billingCountryName)).append("\n");
    sb.append("    billingFullName: ").append(toIndentedString(billingFullName)).append("\n");
    sb.append("    billingPostalCode: ").append(toIndentedString(billingPostalCode)).append("\n");
    sb.append("    billingStateName: ").append(toIndentedString(billingStateName)).append("\n");
    sb.append("    cityName: ").append(toIndentedString(cityName)).append("\n");
    sb.append("    countryName: ").append(toIndentedString(countryName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    namePrefix: ").append(toIndentedString(namePrefix)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    sku: ").append(toIndentedString(sku)).append("\n");
    sb.append("    stateName: ").append(toIndentedString(stateName)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

