/*
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.knetikcloud.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * SearchReferenceMapping
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-29T13:50:55.134-04:00")
public class SearchReferenceMapping {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("new_field_name")
  private String newFieldName = null;

  @JsonProperty("ref_id_field")
  private String refIdField = null;

  @JsonProperty("ref_type")
  private String refType = null;

  @JsonProperty("type")
  private String type = null;

  public SearchReferenceMapping id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the mapping to protect against duplicates
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Unique identifier for the mapping to protect against duplicates")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SearchReferenceMapping newFieldName(String newFieldName) {
    this.newFieldName = newFieldName;
    return this;
  }

   /**
   * The field that will be replaced with the refType
   * @return newFieldName
  **/
  @ApiModelProperty(required = true, value = "The field that will be replaced with the refType")
  public String getNewFieldName() {
    return newFieldName;
  }

  public void setNewFieldName(String newFieldName) {
    this.newFieldName = newFieldName;
  }

  public SearchReferenceMapping refIdField(String refIdField) {
    this.refIdField = refIdField;
    return this;
  }

   /**
   * The path to the id of the referenced resource (can be a field name, or dot notation for sub-fields)
   * @return refIdField
  **/
  @ApiModelProperty(required = true, value = "The path to the id of the referenced resource (can be a field name, or dot notation for sub-fields)")
  public String getRefIdField() {
    return refIdField;
  }

  public void setRefIdField(String refIdField) {
    this.refIdField = refIdField;
  }

  public SearchReferenceMapping refType(String refType) {
    this.refType = refType;
    return this;
  }

   /**
   * The index type that the mapping pulls data from
   * @return refType
  **/
  @ApiModelProperty(required = true, value = "The index type that the mapping pulls data from")
  public String getRefType() {
    return refType;
  }

  public void setRefType(String refType) {
    this.refType = refType;
  }

  public SearchReferenceMapping type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The index type that the mapping is for
   * @return type
  **/
  @ApiModelProperty(required = true, value = "The index type that the mapping is for")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchReferenceMapping searchReferenceMapping = (SearchReferenceMapping) o;
    return Objects.equals(this.id, searchReferenceMapping.id) &&
        Objects.equals(this.newFieldName, searchReferenceMapping.newFieldName) &&
        Objects.equals(this.refIdField, searchReferenceMapping.refIdField) &&
        Objects.equals(this.refType, searchReferenceMapping.refType) &&
        Objects.equals(this.type, searchReferenceMapping.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, newFieldName, refIdField, refType, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchReferenceMapping {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    newFieldName: ").append(toIndentedString(newFieldName)).append("\n");
    sb.append("    refIdField: ").append(toIndentedString(refIdField)).append("\n");
    sb.append("    refType: ").append(toIndentedString(refType)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

