/*
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.knetikcloud.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.knetikcloud.model.SearchReferenceMapping;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * SearchObjectDefinition
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-29T13:50:55.134-04:00")
public class SearchObjectDefinition {
  @JsonProperty("data_supplier_url")
  private String dataSupplierUrl = null;

  @JsonProperty("id_field")
  private String idField = null;

  @JsonProperty("mappings")
  private List<SearchReferenceMapping> mappings = null;

  @JsonProperty("template_field")
  private String templateField = null;

  @JsonProperty("type")
  private String type = null;

  public SearchObjectDefinition dataSupplierUrl(String dataSupplierUrl) {
    this.dataSupplierUrl = dataSupplierUrl;
    return this;
  }

   /**
   * The relative URL of the service that will provide the initial data to index. Assumed to be compliant with KnetikCloud pagination standards. Ex: /locations.
   * @return dataSupplierUrl
  **/
  @ApiModelProperty(value = "The relative URL of the service that will provide the initial data to index. Assumed to be compliant with KnetikCloud pagination standards. Ex: /locations.")
  public String getDataSupplierUrl() {
    return dataSupplierUrl;
  }

  public void setDataSupplierUrl(String dataSupplierUrl) {
    this.dataSupplierUrl = dataSupplierUrl;
  }

  public SearchObjectDefinition idField(String idField) {
    this.idField = idField;
    return this;
  }

   /**
   * The name of the field representing the unique identifier of the document. Ex: UserResource -&gt; id
   * @return idField
  **/
  @ApiModelProperty(value = "The name of the field representing the unique identifier of the document. Ex: UserResource -> id")
  public String getIdField() {
    return idField;
  }

  public void setIdField(String idField) {
    this.idField = idField;
  }

  public SearchObjectDefinition mappings(List<SearchReferenceMapping> mappings) {
    this.mappings = mappings;
    return this;
  }

  public SearchObjectDefinition addMappingsItem(SearchReferenceMapping mappingsItem) {
    if (this.mappings == null) {
      this.mappings = new ArrayList<SearchReferenceMapping>();
    }
    this.mappings.add(mappingsItem);
    return this;
  }

   /**
   * Describe how nested resources should be mapped to documents if needed. Search service will copy the already indexed dependant documents and use them to replace the listed fields at runtime. Ex: comment.user is a user document
   * @return mappings
  **/
  @ApiModelProperty(value = "Describe how nested resources should be mapped to documents if needed. Search service will copy the already indexed dependant documents and use them to replace the listed fields at runtime. Ex: comment.user is a user document")
  public List<SearchReferenceMapping> getMappings() {
    return mappings;
  }

  public void setMappings(List<SearchReferenceMapping> mappings) {
    this.mappings = mappings;
  }

  public SearchObjectDefinition templateField(String templateField) {
    this.templateField = templateField;
    return this;
  }

   /**
   * The name of the property that holds the template ID for custom objects. (ex: template or template_id)
   * @return templateField
  **/
  @ApiModelProperty(value = "The name of the property that holds the template ID for custom objects. (ex: template or template_id)")
  public String getTemplateField() {
    return templateField;
  }

  public void setTemplateField(String templateField) {
    this.templateField = templateField;
  }

  public SearchObjectDefinition type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The name of the index where the documents will be stored. Be convention, the name of the resource w/o suffix. Ex: UserResource -&gt; users
   * @return type
  **/
  @ApiModelProperty(value = "The name of the index where the documents will be stored. Be convention, the name of the resource w/o suffix. Ex: UserResource -> users")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchObjectDefinition searchObjectDefinition = (SearchObjectDefinition) o;
    return Objects.equals(this.dataSupplierUrl, searchObjectDefinition.dataSupplierUrl) &&
        Objects.equals(this.idField, searchObjectDefinition.idField) &&
        Objects.equals(this.mappings, searchObjectDefinition.mappings) &&
        Objects.equals(this.templateField, searchObjectDefinition.templateField) &&
        Objects.equals(this.type, searchObjectDefinition.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataSupplierUrl, idField, mappings, templateField, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchObjectDefinition {\n");
    
    sb.append("    dataSupplierUrl: ").append(toIndentedString(dataSupplierUrl)).append("\n");
    sb.append("    idField: ").append(toIndentedString(idField)).append("\n");
    sb.append("    mappings: ").append(toIndentedString(mappings)).append("\n");
    sb.append("    templateField: ").append(toIndentedString(templateField)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

